require 'io/console'
require 'sinatra'
require 'sinatra/cross_origin'
require 'active_support/inflector'
require 'sanitize'
require 'string-urlize'
require 'securerandom'
require 'digest'
require 'json'
require 'wannabe_bool'
require 'envyable' if @Env == 'development'